# Generated by Django 5.1.3 on 2024-11-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_userprofile_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
