# Generated by Django 5.1.3 on 2024-11-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_userprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
