# Generated by Django 5.1.3 on 2024-11-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_cvstructure_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetterStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
        ),
    ]
